Module7 task1
htmlacademy-ecmascript/1174641-big-trip-15 pull request #10
Opened 2021-09-01 20:32 UTC by InkMakhova

2021-09-01 21:31 UTC, andreevsm requested changes

2021-09-01 21:31 UTC, andreevsm commented on src/utils/common.js
> +// export const updateItem = (items, update) => {
Удаляем?

2021-09-01 21:31 UTC, andreevsm commented on src/view/point-list-empty.js
> +  constructor (data) {
Нарушение критерия - необходимо давать название согласно бизнес-логике или контексту, в котором используется переменная
Тут, очевидно, должен быть `filterType` )

2021-09-01 21:31 UTC, andreevsm commented on src/view/site-menu.js
> +    const itemActive = Array.from(this.getElement().querySelectorAll('a'))
Эта часть `Array.from(this.getElement().querySelectorAll('a'))`, давай вынесем в отдельную переменную

2021-09-01 21:31 UTC, andreevsm commented on src/presenter/point-new.js
> +    this._pointEditComponent = new PointFormView('new', this._data, this._destinations);
Давай вынесем в константы `'new'` по аналогии с UserAction и UpdateType

2021-09-02 05:37 UTC, InkMakhova commented on src/utils/common.js
> +// export const updateItem = (items, update) => {
удалила

2021-09-02 05:37 UTC, InkMakhova commented on src/view/point-list-empty.js
> +  constructor (data) {
ок, переименовала

2021-09-02 05:40 UTC, InkMakhova commented on src/view/site-menu.js
> +    const itemActive = Array.from(this.getElement().querySelectorAll('a'))
добавила переменную

2021-09-02 06:03 UTC, InkMakhova commented on src/presenter/point-new.js
> +    this._pointEditComponent = new PointFormView('new', this._data, this._destinations);
вынесла в FormType

2021-09-02 10:39 UTC, merged