Module7 task2
htmlacademy-ecmascript/1174641-big-trip-15 pull request #11
Opened 2021-09-04 08:42 UTC by InkMakhova

2021-09-04 21:56 UTC, andreevsm requested changes

2021-09-04 21:56 UTC, andreevsm commented on src/constants.js
> +export const TYPES = Object.values(PointTypes);
Давай уточним, что это `POINT_TYPES`

2021-09-04 21:56 UTC, andreevsm commented on src/view/button-new-point.js
> +  deactivateButton() {
Не проще `disableButton`?)

2021-09-04 21:56 UTC, andreevsm commented on src/view/statistics.js
> +    options: {
Эти объекты во многих полях повторяются. Давай подумаем о вынесении его в отдельную функцию (лучше даже в другом файле, чтоб не засорять statistics.js) и передавать в нее нужные параметры

2021-09-05 06:22 UTC, InkMakhova commented on src/constants.js
> +export const TYPES = Object.values(PointTypes);
ок, исправила

2021-09-05 06:29 UTC, InkMakhova commented on src/view/button-new-point.js
> +  deactivateButton() {
ok

2021-09-05 07:59 UTC, InkMakhova commented on src/view/statistics.js
> +    options: {
сделано

2021-09-05 20:04 UTC, andreevsm approved these changes

2021-09-05 20:04 UTC, andreevsm commented on src/view/statistics.js
> +  return new Chart(timeCtx,  createChartTemplate(uniqTypesUpperCase, pointByTypeCounts, hexTypes, null, formatDuration));
Воо красота!

2021-09-05 20:04 UTC, merged