Module8 task1
htmlacademy-ecmascript/1174641-big-trip-15 pull request #12
Opened 2021-09-08 13:10 UTC by InkMakhova

2021-09-08 18:13 UTC, andreevsm requested changes

2021-09-08 18:13 UTC, andreevsm commented on src/api.js
> +  _load({
Хм, метод load что-то должен загружать, а получается, что он и обновляет и удаляет
Давай дадим более подходящее название. Например, `_api`, либо даже `_fetch`

2021-09-08 18:13 UTC, andreevsm commented on src/main.js
> +//import {destinations} from './mock/destinations.js';
Мы ведь перешли на реальные данные, предлагаю почистить все, что связано с моками

2021-09-08 18:13 UTC, andreevsm commented on src/presenter/point-new.js
> +    //this.destroy();
Удаляем?

2021-09-08 18:13 UTC, andreevsm commented on src/presenter/point.js
> +      //replace(this._pointEditComponent, prevPointEditComponent);
Удаляем?
Пройдись по файлам, много где подобных комментов)

2021-09-08 18:16 UTC, andreevsm commented
Почему-то в новой точке нельзя выбрать дату начала завтра

![image](https://user-images.githubusercontent.com/26060516/132562623-5e0f9165-002e-414d-9475-52ecab89f472.png)

2021-09-08 18:16 UTC, andreevsm commented
Также варнинги в консоли, от них лучше избавиться

![image](https://user-images.githubusercontent.com/26060516/132562979-c5b0fbfa-95ce-4126-997f-ce86693015e3.png)

2021-09-08 18:17 UTC, andreevsm commented
И кажется, что offers не обновляются при изменении города

2021-09-09 10:38 UTC, InkMakhova commented on src/api.js
> +  _load({
переименовала на _fetch

2021-09-09 11:12 UTC, InkMakhova commented on src/main.js
> +//import {destinations} from './mock/destinations.js';
удалила

2021-09-09 11:12 UTC, InkMakhova commented on src/presenter/point-new.js
> +    //this.destroy();
удалила

2021-09-09 11:13 UTC, InkMakhova commented on src/presenter/point.js
> +      //replace(this._pointEditComponent, prevPointEditComponent);
все почистила

2021-09-09 16:37 UTC, merged