Module2 task1
htmlacademy-ecmascript/1174641-big-trip-15 pull request #4
Opened 2021-08-04 16:52 UTC by InkMakhova

2021-08-04 16:55 UTC, InkMakhova commented
Форма добавления новой точки добавляется по кнопке New Event, данные в ней только по дефолтному типу (flyght), к нему добавляются offers, остальное пустое (оставила как в жизни должно быть)

2021-08-04 17:26 UTC, andreevsm requested changes

2021-08-04 17:26 UTC, andreevsm commented on package.json
> +    "dayjs": "^1.10.6"
Давай жестко фиксировать зависимости, то есть необходимо установить без `~` и `^`

2021-08-04 17:26 UTC, andreevsm commented on src/constants.js
> +export const OFFERS_BY_TYPE = [
Предлагаю удалить этот массив, вынести offers (в небольшом количестве) в отдельный массив и уже рандомно генерировать объект типа
```
const randomPoint = {
  type: POINT_TYPES[random],
  offers: OFFERS.slice(fromRandom ,toRandom)
}
```
Точнее это у тебя будет функция, возвращающая такой вот рандомный объект. И не придется хранить массив в 140 строчек)

2021-08-04 17:26 UTC, andreevsm commented on src/main.js
> +const points = new Array(POINTS_NUMBER).fill(null).map(() => generateDataPoint());
Лучше попробуй вот такой способ создания массива на основе числа:
```
Array.from({ length: 5 }, (v, k) => k);
// // [0, 1, 2, 3, 4]
```
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from

2021-08-04 17:26 UTC, andreevsm commented on src/main.js
> +  if (evt.target.value === 'everything') {
Прям напрашивается switch case для `evt.target.value` вместо `if`

2021-08-04 17:26 UTC, andreevsm commented on src/main.js
> +  if (evt.target.value === 'sort-price') {
Тут тоже)

2021-08-04 17:26 UTC, andreevsm commented on src/main.js
> +// const loadData = (onSuccess, onFail) => {
Удаляем?

2021-08-04 17:26 UTC, andreevsm commented on src/view/add-edit-point.js
> +const createOffersSection = (dataObject, eventType) => {
Предлагаю вынести темплейты из этой функции, чтоб было примерно вот так:
```
const createOffersSection = () => {
  if (eventType === 'new') {
    return firstTemplate();
  }
  
  if (dataObject.offer && dataObject.offer.length > 0) {
    return secondTemplate();
  }
}
```

Так просто читабельнее получается

2021-08-05 06:07 UTC, InkMakhova commented on package.json
> +    "dayjs": "^1.10.6"
исправлено

2021-08-05 07:01 UTC, InkMakhova commented on src/constants.js
> +export const OFFERS_BY_TYPE = [
исправлено

2021-08-05 07:23 UTC, InkMakhova commented on src/main.js
> +const points = new Array(POINTS_NUMBER).fill(null).map(() => generateDataPoint());
исправила

2021-08-05 07:48 UTC, InkMakhova commented on src/main.js
> +  if (evt.target.value === 'everything') {
исправила

2021-08-05 07:48 UTC, InkMakhova commented on src/main.js
> +  if (evt.target.value === 'sort-price') {
исправила

2021-08-05 08:18 UTC, InkMakhova commented on src/main.js
> +// const loadData = (onSuccess, onFail) => {
да, лишнее

2021-08-05 13:45 UTC, andreevsm requested changes

2021-08-05 13:45 UTC, andreevsm commented on src/main.js
> +// const loadData = (onSuccess, onFail) => {
Так а шо не удалила?)

2021-08-05 13:45 UTC, andreevsm commented on src/main.js
> +    case 'everything':
Раз уж придется делать коммит с удалением коммента, то давай ещё тут поправим
Всегда когда используешь конструкцию `switch case`, обязательно добавляй в конце `default`, мало ли какое значение придет))
Здесь кстати можно убрать case с `everything` и перенести эту логику в default

И тоже самое нужно для сортировки сделать)

2021-08-05 14:35 UTC, InkMakhova commented on src/main.js
> +// const loadData = (onSuccess, onFail) => {
я удалила строку points.map((point) => render(tripEnventsListElement, createPointTemplate(point)));😇
 
loadData удалила сейчас

2021-08-05 14:43 UTC, InkMakhova commented on src/main.js
> +    case 'everything':
поправила: в фильтрах перенесла  работу 'everything' в default, а в сортировке 'sort-day' в default

2021-08-05 16:23 UTC, merged