Module3 task1
htmlacademy-ecmascript/1174641-big-trip-15 pull request #5
Opened 2021-08-08 15:16 UTC by InkMakhova

2021-08-08 19:03 UTC, andreevsm requested changes

2021-08-08 19:03 UTC, andreevsm commented on src/util.js
> +const ESC_KEY = ['Escape', 'Esc'];
Задумка с константой правильная, но в данном случае в ней нет необходимости - она нигде кроме этого файла не используется (и то в одном месте)
Поэтому можно смело сделать `export const isEscEvent = (evt) => ['Escape', 'Esc'].includes(evt.key);`

2021-08-08 19:03 UTC, andreevsm commented on src/view/point.js
> +  const favoriteClassName = isFavorite === true ? ' event__favorite-btn--active' : '';
Может сделаем просто
```
const favoriteClassName = isFavorite ? ' event__favorite-btn--active' : '';
```

2021-08-09 06:33 UTC, InkMakhova commented on src/presenter/filters-presenter.js
> +export const getFilteredPoints = (dataPoints, filterName) => {
ок, поправила параметр в фильтрах и сортировке

2021-08-09 06:37 UTC, InkMakhova commented on src/util.js
> +const ESC_KEY = ['Escape', 'Esc'];
поправила

2021-08-09 06:38 UTC, InkMakhova commented on src/view/point.js
> +  const favoriteClassName = isFavorite === true ? ' event__favorite-btn--active' : '';
точно, поправила)

2021-08-09 16:09 UTC, merged